### ISSUE TITLE
Problems with releasing new plugin version

### ISSUE THREAD

**Issue by mkuculyma** [intelsdi-x/snap-plugin-publisher-influxdb#127]
After adding the tag for the new plugin version:
```
git tag -a 22 -m 'snap plugin publisher influxdb v22'
git push origin 22
```
publishing the release binary is not triggered. 
cc @nanliu

**Comment by nanliu** [comment]
@mkuculyma, PR #124 broke travis configuration. The matrix exclusion stopped building go  1.6.x, and it stopped building go 1.7.x releases and 1.7.x large tests:

```
matrix:
  exclude:
  - go: 1.7.x
    env: SNAP_VERSION=latest TEST_TYPE=large
  - go: 1.7.x
    env: SNAP_VERSION=latest_build TEST_TYPE=large
  - go: 1.7.x
    env: TEST_TYPE=build
```

We are no longer building new binaries or releasing at this point. We should delete tag 22, fix the matrix and re-release tag 22.
